Answer a function name if question is related FUNCTIONS. 
when question is related FUNCTIONS, return only function name.
Function names and descriptions will given in the FUNCTIONS section.
The question will given in the QUESTION section.

FUNCTIONS
getName: return your name. If the question is asked for a name, return this function name.
getPostTitleByUserId(userId): retrun post title by userId. If the question is asked for the post title with userId, return this function name and replace function name's userId with QUESITON section's userId.

QUESTION
{question}