package com.example.chatbot.common.constant;

public class Constant {
    public static final String DOCUMENT_EXAMPLE_COUPANG ="""
        The first marketplace and largest online retailer in South Korea, Coupang's annual revenue as of 2021 is US $18.4 billion. The company's Rocket Delivery network provides same-day or next-day delivery of more than five million unique items. Coupang claims that 99.6 percent of its orders are delivered within 24 hours. 70% of Korean citizens live within 10 minutes of a Coupang logistic center.
        Coupang was headquartered in Seoul, South Korea, in the Songpa-gu District until 2022 when it relocated to Seattle in the US. Coupang also has offices in Beijing, Shanghai, Los Angeles and Mountain View. It is incorporated in Delaware, United States.
        Coupang was founded by Bom Kim in 2010. A student of Harvard University, Kim started to study for his MBA at Harvard Business School but dropped out six months into the program.
        Kim registered Coupang as a limited liability company in the US, allowing to access US funding. In November 2018, Coupang received a US$2 billion investment from SoftBank. Other major investors in Coupang include BlackRock and Fidelity.
        The company has grown during the COVID-19 pandemic with increased demand for online shopping. In July 2020, Coupang acquired the assets of Singaporean streaming service HOOQ to form the nucleus of its streaming service named Coupang Play.
        Coupang had its IPO on the New York Stock Exchange on 11 March 2021.
        On 4 June 2021, Coupang announced that it had started trial operations in Japan. However it pulled out of the country less than 2 years later due to low growth potential amid the dominance of Amazon and local player Rakuten. On 8 July 2021, the company launched in Taiwan.
        On 18 December 2023, Coupang announced it would be acquiring online retailer Farfetch in a deal that would give Farfetch access to $500 million worth of capital. The deal comes as Farfetch faced potential administration, with previous talks with Swiss luxury group Richemont being terminated
    """;

    public static final String DOCUMENT_EXAMPLE_SAMSUNG ="""
        Samsung Group[3] (Korean: 삼성; Hanja: 三星; RR: samseong [samsʌŋ]; stylized as SΛMSUNG) is a South Korean multinational manufacturing conglomerate headquartered in Samsung Digital City, Suwon, South Korea.[1] It comprises numerous affiliated businesses,[1] most of them united under the Samsung brand, and is the largest South Korean chaebol (business conglomerate). As of 2020, Samsung has the world's eighth-highest brand value.[4]
        Samsung was founded by Lee Byung-chul in 1938 as a trading company. Over the next three decades, the group diversified into areas including food processing, textiles, insurance, securities, and retail. Samsung entered the electronics industry in the late 1960s and the construction and shipbuilding industries in the mid-1970s; these areas would drive its subsequent growth. Following Lee's death in 1987, Samsung was separated into five business groups – Samsung Group, Shinsegae Group, CJ Group and Hansol Group, and JoongAng Group.
        Notable Samsung industrial affiliates include Samsung Electronics (the world's largest information technology company, consumer electronics maker and chipmaker measured by 2017 revenues),[5][6] Samsung Heavy Industries (the world's second largest shipbuilder measured by 2010 revenues),[7] and Samsung Engineering and Samsung C&T Corporation (respectively the world's 13th and 36th largest construction companies).[8] Other notable subsidiaries include Samsung Life Insurance (the world's 14th largest life insurance company),[9] Samsung Everland (operator of Everland Resort, the oldest theme park in South Korea)[10] and Cheil Worldwide (the world's 15th largest advertising agency, as measured by 2012 revenues).[11][12]
    """;

    public static final String DOCUMENT_EXAMPLE_LG ="""
        LG Corporation was established as Lak Hui Chemical Industrial Corp. in 1947 by Koo In-hwoi.[4] In 1952, Lak Hui (락희) (pronounced "Lucky"; now LG Chem) became the first South Korean company to enter the plastics industry. As the company expanded its plastics business, it established GoldStar Co. Ltd. (now LG Electronics Inc.) in 1958. Both companies Lucky and GoldStar merged to form Lucky-Goldstar in 1983.[5]
        GoldStar produced South Korea's first radio.[5] Many consumer electronics were sold under the brand name GoldStar, while some other household products (not available outside South Korea) were sold under the brand name of Lucky. The Lucky brand was famous for hygiene products such as soaps and HiTi laundry detergents, but the brand was mostly associated with its Lucky and Perioe toothpaste. LG continues to manufacture some of these products for the South Korean market, such as laundry detergent.
        Koo In-hwoi led the corporation until his death in 1969, at which time, his son Koo Cha-kyung took over. He then passed the leadership to his son, Koo Bon-moo, in 1995. Koo Bon-moo renamed the company to LG in that year.[5] The company also associates the letters LG with the company's tagline "Life's Good". Since 2009, LG has owned the domain name LG.com.
        Koo Bon-moo died of a brain tumor on 20 May 2018.[6] In July 2018, it was announced that Koo Kwang-mo, the nephew and adopted son of Koo Bon-moo, will be the new CEO of LG. Koo Bon-moo adopted his nephew in 2004, after losing his only son in 1994,[7] citing "a family tradition of male-only succession".[8]
        On 31 July 2021, LG Electronics officially ended its mobile phone business, disappearing into history 26 years after its inception.
    """;

    public static final String DOCUMENT_EXAMPLE_SK ="""
        SK Group (Korean: SK그룹, 에스케이그룹) is a South Korean multinational manufacturing and services conglomerate headquartered in Seoul. A chaebol (Korean family-owned conglomerate), SK Group is second largest such conglomerate by revenue in South Korea, after Samsung Group. Through a number of subsidiaries, it is engaged in various businesses, including manufacture of chemicals and petrochemicals, semiconductors, flash memory and miscellaneous information technology, as well providing telecommunications services worldwide among its other less notable ventures.
        The conglomerate is composed of 186 subsidiaries and affiliates that share the SK brand name and the group's management culture, named SKMS (SK Management System). It changed its name from Sunkyong Group (Korean: 선경그룹, Hanja: 鮮京그룹) to SK Group in 1998. The group is controlled by estate of Chey Tae-won through a holding company, SK Inc. The cornerstone of SK Group is its energy and chemicals division.[2]
        While its largest businesses are primarily involved in the energy, petroleum, and chemical industries, the group also owns the nation's largest wireless mobile phone service provider SK Telecom, and provides services in construction, marketing, local telephone communications, high-speed internet, and wireless broadband WiBro. Since 2012, SK Hynix, one of the world's largest random access memory and semiconductor manufacturers, has also been majority owned by the group.
    """;
}
